[build]
  # No build command needed for static site
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Form handling configuration
[[forms]]
  name = "contact"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect rules for clean URLs
[[redirects]]
  from = "/inicio"
  to = "/"
  status = 301

# Clean URLs - Remove .html extension
# Rewrite clean URLs to .html files (user sees clean URL)
[[redirects]]
  from = "/contacto"
  to = "/contacto.html"
  status = 200

[[redirects]]
  from = "/servicios"
  to = "/servicios.html"
  status = 200

[[redirects]]
  from = "/equipo"
  to = "/equipo.html"
  status = 200

[[redirects]]
  from = "/instalaciones"
  to = "/instalaciones.html"
  status = 200

# Redirect .html URLs to clean URLs (SEO friendly)
[[redirects]]
  from = "/contacto.html"
  to = "/contacto"
  status = 301

[[redirects]]
  from = "/servicios.html"
  to = "/servicios"
  status = 301

[[redirects]]
  from = "/equipo.html"
  to = "/equipo"
  status = 301

[[redirects]]
  from = "/instalaciones.html"
  to = "/instalaciones"
  status = 301

# Success page clean URL
[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/success.html"
  to = "/success"
  status = 301

# Handle Spanish/Catalan/English routing
[[redirects]]
  from = "/es/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/ca/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/:splat"
  status = 200
